### PR TITLE
Upgrade to latest alpine 3.4 version

### PR DESCRIPTION
**Pull request by eko**
This pull request upgrades this repository to the latest Alpine version, see: http://alpinelinux.org/posts/Alpine-3.4.0-released.html

### CODE REVIEW

**Comment by guillemcanal** [comment]
Can you confirm that the PHP FPM binary is still `php-fpm` ? If not, you may have to update https://github.com/guillemcanal/alpine-nginx-php/blob/master/rootfs/etc/services.d/php-fpm/run

Thanks mate

**Comment by eko** [comment]
@guillemcanal You were right, I've updated the PR, container now builds & run correctly ;)

**Comment by guillemcanal** [comment]
Hey! I'll review again you PR this afternoon. It will be merged in a short while ;)

**Comment by eko** [comment]
Do you still need this PR or can I close it? Alpine is now version 3.5 ;)

**Pull request closed without merging**
